---
title: "Resume"
author: "Steven Lawrence"
date: "July 16, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Education
Columbia University Mailman School of Public Health:
Master of Science (MS) in Biostatistics Candidate (May 2021)

The City University of New York (CUNY) Medgar Evers College:
Bachelor of Science (BS) in Biology (Mathematics Minor) (June 2019)

The City University of New York (CUNY) Medgar Evers College:
Associates of Science (AS) (June 2016)

## Skills
Languages: English, Jamaican Patois
Statistical Software/Computer Programming: R, R-Studio, REDCap, SAS, SQL
Statistics & Research Methodology: Disparity Analytics, Time Series Analysis (Coursera certificate), Heart Rate Variability Analysis (R package development in progress), Biostatistical Methods

## Experience (Short)  
1.  Teacher assistant at the R studio conference for a time series workshop 
2.  Teacher assistant at ENAR Fostering Diversity Workshop 
3.  Served on the committe for assessing the racial climate of the Biostatistic deparment at Mailman
4.  Consultant to Mount Sinai's Neurology Department. 
5.  Graduate Research Assistant in Data Science and Statistics at the Center for Scientific Diversity at the Icahn School of medicine at Mount Sinai
6.  Volunteer in the Center for Biostatistics department of population health science and police at the Icahn School of medicine at Mount Sinai

## Project Highlights

1. Geographic Distribution and temporal analysis of Google Trend Data using Skin Bleashing queries as a proxy for its behavior. 

2. Honorary mention for bivariate visualizations from This Is Statistics (ASA) data challenge to address the Opioid epidemic. 

## Publicaions

1. Jessica Robinson-Papp, Alexandra Nmashie, Elizabeth Pedowitz, Mary Catherine George, Sandeep Sharma, Jacinta
Murray, Emma K. T. Benn, Steven A. Lawrence, Josef Machac, Sherif Heiba, Seunghee Kim-Schulze, Allison Navis,
Bani Chander Roland, Susan Morgello. (2019) The effect of pyridostigmine on gastrointestinal function and inflammatory
markers in HIV associated autonomic neuropathy. Journal of NeuroVirology 25(4): 551-559.

2. Michelle Odlum, Danielle Black, Sunmoo Yoon, Cassidy Maher, Steven Lawrence, Jennel Osborne. (2019) Exploring
HIV Concern in A Population of Dominican American Women Midlife and Older. BMC Public Health (In Press)

3. Steven Lawrence and Jean Jean-Michel. Combinatorial mathematics used to solve fundamental biological
problems. (In Preparation)

4. Steven Lawrence, Bian Liu, Richa Deshpande, Hector Moran, Eleanor Holder, Florentino Caetano Dos Santos, Irmina
Michalek, Sharon Gordon, Liangyuan Hu, Emma K. T. Benn. Estimating the Geographic Distribution of Skin Bleaching
in the US: an application of query search surveillance using Google Trends Data. (In Preparation)

# Email for full CV sl4269@cumc.columbia.edu 